# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
